### ISSUE TITLE
Updating entries to MAL clears started/finished dates.

### ISSUE THREAD

**Issue by Vectri** [ccubed/PyMoe#17]
I noticed that after updating scores in bulk the completion dates I had set for anime I have watched were cleared.

Relevant code:

```
mal = Mal("username", "password")
user_anime_list = mal.user("example").anime.list
user_completed_anime_list = [anime.title for anime in user_anime_list if anime.status.user == "Completed"]
modified_scores_list = {'example': 10}

def update_scores(modified_scores_list):
    for anime in user_anime_list:
        if user_completed_anime_list.__contains__(anime.title) and modified_scores_list[anime.title.lower()]:
            anime.scores.user = modified_scores_list[anime.title.lower()]
            mal.anime.update(anime)
```

**Comment by ccubed** [comment]
I have confirmed that there are times that requesting user data returns no dates. I have not confirmed why. I will give more information once I have determined the exact cause.

**Comment by ccubed** [comment]
So here's the thing. When I did this last night, it was happening. I then went to bed. Fast forward a couple hours. I wake up and decide to do some testing on the latest master branch. However, this problem is no longer occurring. I can't reproduce it. So, for now, I have added some checks to make sure that we're getting 200's back from the endpoints before assuming the data is good. I don't think this is the problem by any means because series dates were fine. However, I don't have any reason to believe there's anything wrong with Pymoe. Perhaps it was just a fluke with the MAL endpoint, maybe it was someone doing testing, maybe it really was some weird conversion issue with Pymoe. In any case, All I can do at this point is mark it as something I'm aware of. If you see it again, let me know.
