### ISSUE TITLE
Crashes when specified id doesn't exist on anilist.co

### ISSUE THREAD

**Issue by K0-RR** [ccubed/PyMoe#38]
Code:
```
import pymoe
print(pymoe.anime.get.show(13412))
```
output:
```
    print(pymoe.anime.get.show(13412))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Lenovo/.local/lib/python3.11/site-packages/pymoe/anime/get/__init__.py", line 18, in show
    return anilist.show(item_id)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Lenovo/.local/lib/python3.11/site-packages/pymoe/anime/get/anilist/__init__.py", line 175, in show
    raise serverError(r.text, r.status_code)
pymoe.errors.serverError: ('{"errors":[{"message":"Not Found.","status":404,"locations":[{"line":3,"column":13}]}],"data":{"Media":null}}', 404)
```

**Comment by ccubed** [comment]
This is intentional behavior. If the server returns an error code, we raise an error to return the error code and the returned content to make determining the issue easier. In addition, I subclassed exception to make it easier to understand where the errors are being produced. By subclassing Exception you can still catch it using the built in Exception class but it will return as a moeError type making it clear which library raised it. If you want to catch and react to the error, you could use the builtin Exception which my moeError class inherits, moeError itself, or the specific errors that might occur (Typically only serverError).
